title: Bike gloves
hero_image: images/banner.png
description: Create flashing bike gloves and stay safe when riding in the dark!
listed: false
pdf: false
steps:
  - title: What you will make
  - title: Make a prototype
    completion:
      - engaged     
  - title: Add to your gloves 
  - title: Challenge
    challenge: true
    completion:
      - external
