title: Bike gloves
hero_image: images/banner.png
description: Create flashing bike gloves to help you stay safe when cycling in the dark
listed: true
pdf: false
steps:
  - title: What you will make
  - title: Make a prototype
    completion:
      - engaged     
  - title: Add to your gloves 
  - title: Challenge
    challenge: true
    completion:
      - external
